import { fontVariableClassNames } from "@/styles/fonts";
import type { Metadata } from "next";
import "../styles/globals.css";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontVariableClassNames} antialiased font-open-sans`}>
        {children}
      </body>
    </html>
  );
}
