import { baseStyles } from "@/styles";
import type { Metadata } from "next";
import "../styles/globals.css";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={baseStyles}>{children}</body>
    </html>
  );
}
