import { baseStyles } from "@/styles";
import type { Metadata } from "next";
import "../styles/globals.css";
import type { ReactNode } from "react";

// recommended NextJS config: https://docs.fontawesome.com/web/use-with/react/use-with#nextjs
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={baseStyles}>{children}</body>
    </html>
  );
}
